### ISSUE TITLE
Can you release the compiled program file?

### ISSUE THREAD

**Issue by ziming2018** [iamvucms/react-native-instagram-clone#10]
I want to learn react-native through your project, But I did not compile successfully.

**Comment by iamvucms** [comment]
Sure. I don't work much time on Android but here is Android release apk file and It doesn't have a lot of errors. ^^/Users/vucms/Desktop/REACT-NATIVE/Instagram/android/app/build/outputs/apk/release/app-release.apk

**Comment by iamvucms** [comment]
Sure. I don't work much time on Android but here is Android release apk file and It doesn't have a lot of errors.
Download at: https://secufiles.com/aYb3/app-release.apk
Good luck.

**Comment by ziming2018** [comment]
Thank you very much. Do you have a login password?

**Comment by iamvucms** [comment]
vucms
vucms0202
You can create your own one but you can't create post because classify server hasn't been puslished.
Good luck

**Comment by ziming2018** [comment]
Okay thank you
