### ISSUE TITLE
AccountStack missing unique key for prop

### ISSUE THREAD

**Issue by ReallyCoolGuy** [iamvucms/react-native-instagram-clone#3]
![image](https://user-images.githubusercontent.com/68084072/87090553-2d127c80-c206-11ea-9f30-d220e6204ba2.png)

**Comment by iamvucms** [comment]
Thanks for your contribution,
The fix will appear in the next commit 
![image](https://user-images.githubusercontent.com/17398401/87116534-410abc80-c2a0-11ea-828c-07e133ca13ce.png)
