### ISSUE TITLE
GoogleService-Info.plist fails

### ISSUE THREAD

**Issue by johuder33** [iamvucms/react-native-instagram-clone#6]
By running the RN app it throws an error related to `GoogleService-Info.plist`, it seems it's missing the instructions related to this in the README, i just want you to know about it 👍 

```
** BUILD FAILED **


The following build commands failed:
	CopyPlistFile /Users/___/Library/Developer/Xcode/DerivedData/Instagram-afliumfqepwmqiaspiuvagdyjufe/Build/Products/Debug-iphonesimulator/Instagram.app/GoogleService-Info.plist /Users/Downloads/GoogleService-Info.plist
(1 failure)
```

**Comment by iamvucms** [comment]
try
```bash
yarn remove @react-native-firebase
yarn remove @react-native-firebase/app
yarn remove @react-native-firebase/firestore
npx pod-update
```
Then remove 2 lines in src/ios/{projectName}/AppDelegate.m
```
#import <Firebase.h><----remove
[FIRApp configure];<---remove
```

**Comment by huytrinh68** [comment]
> try
> 
> ```shell
> yarn remove @react-native-firebase
> yarn remove @react-native-firebase/app
> yarn remove @react-native-firebase/firestore
> npx pod-update
> ```
> 
> Then remove 2 lines in src/ios/{projectName}/AppDelegate.m
> 
> ```
> #import <Firebase.h><----remove
> [FIRApp configure];<---remove
> ```

I tried but it not work

**Comment by iamvucms** [comment]
Hi, 
Did you close all metro console and  re-run react-native run-ios

**Comment by Dr1992** [comment]
It's because your GoogleService-Info.plist was in your downloads folder so you need to put GoogleService-Info.plist in the ios folder and import from there into xcode

**Comment by jb29611** [comment]
Hello,

I'm getting the same error as huytrin68.  :(

**Comment by iamvucms** [comment]
Hello all,
GoogleService-Info.plist is just a mistake, **firebase** npm package on my project, It's not **react-native-firebase**
First close all metro console window\
Try remove GoogleService-Info.plist
```bash
yarn remove @react-native-firebase
yarn remove @react-native-firebase/app
yarn remove @react-native-firebase/firestore
npx pod-update
```
Then remove 2 lines in src/ios/{projectName}/AppDelegate.m
```
#import <Firebase.h><----remove
[FIRApp configure];<---remove
```
And restart project:
```bash
react-native run-ios
```
Good luck!

**Comment by jb29611** [comment]
Hello everyone,

Thanks iamvucms.

I got it working by removing - 
react-native-firebase, @react-native-firebase/app, yarn remove @react-native-firebase/firestore.
and then removed the following from src/ios/{projectName}/AppDelegate.m

```
import <Firebase.h>
`[FireApp configure'] `
```
and also 
(line22)
`B8B92A27244457A800255790 /* GoogleService-Info.plist in Resources */ = {isa = PBXBuildFile; fileRef = B8B92A26244457A800255790 /* GoogleService-Info.plist */; }; `

I hope it helps.

Thanks again.

**Comment by iamvucms** [comment]
Hello all,
I updated at the newest commit.
Try it again
Good luck.
