### ISSUE TITLE
Firebase security rules

### ISSUE THREAD

**Issue by gezginkola** [iamvucms/react-native-instagram-clone#8]
Hi, thanks for this great effort👍 Can you please share the Firebase security rules?
Best

**Comment by iamvucms** [comment]
Sure, but I dIdn't write it carefully, I'm still just a newbie in firebase ^^
rules_version = '2';

service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth.uid != null;
    }
    match /{path=**}/comments/{id} {
    	allow read, write: if request.auth.uid != null;
    }
    match /{path=**}/comments/{id}/replies/{id2} {
    	allow read, write: if request.auth.uid != null;
    }
    match /{path=**}/users/{id} {
      allow read, write: if true;
    }
  }
}

**Comment by gezginkola** [comment]
thanks a lot iamvucms,
I am able to add posts or comment or like etc but if i try to share a post to a user i got permission issues.

Forexample, getting permision errors like '@firebase/database:, FIREBASE WARNING: set at /messages/user1/user2/1599843996361 failed: permission_denied' 
or
 anopther one  like ' @firebase/database:, FIREBASE WARNING: update at /online/user1 failed: permission_denied'

Can you please suggest what i am missing?
Note: i have added your securty rules still getting same errors.
Thanks You.

**Comment by iamvucms** [comment]
Hi, 
Above rule is firestore's rule , I've just granted permission for all, try again.

**Comment by gezginkola** [comment]
![image](https://user-images.githubusercontent.com/50251835/92956291-4f777f00-f46f-11ea-9a76-b84c2bd882f3.png)
yes i also did same rules on firestore you can see the image. however still getting same errors above message.

**Comment by iamvucms** [comment]
But I save  messages in realtime database
add this rule 
{
  "rules": {
    ".read": true,
    ".write": true
  }
}
to your realtime database's rule. Good luck

**Comment by gezginkola** [comment]
ahhh:( got it. that is my fault. now i am able to share posts. Thanks alot.
