### ISSUE TITLE
database

### ISSUE THREAD

**Issue by sootood** [iamvucms/react-native-instagram-clone#9]
is it possible for you to show your data base in cloud firestore?

**Comment by iamvucms** [comment]
Sure but I can't create backup from firebase to dump or json file.
You can get it over below images and reducer files in my project:
![image](https://user-images.githubusercontent.com/17398401/93223239-0b032080-f79a-11ea-909e-fec1cc23d0bc.png)
![image](https://user-images.githubusercontent.com/17398401/93223270-122a2e80-f79a-11ea-8750-a6f37b1e0946.png)
![image](https://user-images.githubusercontent.com/17398401/93223300-1a826980-f79a-11ea-8fe6-180a7b953958.png)
![image](https://user-images.githubusercontent.com/17398401/93223327-253cfe80-f79a-11ea-9465-4a3be00a6c2b.png)
![image](https://user-images.githubusercontent.com/17398401/93223354-2d953980-f79a-11ea-8a64-7e077eff4556.png)
![image](https://user-images.githubusercontent.com/17398401/93223389-36860b00-f79a-11ea-9291-470d4405f242.png)
![image](https://user-images.githubusercontent.com/17398401/93223505-56b5ca00-f79a-11ea-8c82-e153a0c27859.png)
![image](https://user-images.githubusercontent.com/17398401/93223528-5d444180-f79a-11ea-87c0-3b4578bbb7a1.png)
![image](https://user-images.githubusercontent.com/17398401/93223561-66351300-f79a-11ea-81a8-0294d57df460.png)
![image](https://user-images.githubusercontent.com/17398401/93223605-70571180-f79a-11ea-96b8-d56e18f436c5.png)
![image](https://user-images.githubusercontent.com/17398401/93223626-777e1f80-f79a-11ea-8b68-d90040e3dfea.png)
![image](https://user-images.githubusercontent.com/17398401/93223669-8238b480-f79a-11ea-8307-d469009f587f.png)
![image](https://user-images.githubusercontent.com/17398401/93223712-8cf34980-f79a-11ea-8bb0-ff5b8fbc1ecc.png)
![image](https://user-images.githubusercontent.com/17398401/93223768-9aa8cf00-f79a-11ea-88b7-74632ed07d96.png)
![image](https://user-images.githubusercontent.com/17398401/93223789-a0061980-f79a-11ea-9482-ed2d1b2e238c.png)
![image](https://user-images.githubusercontent.com/17398401/93223810-a4cacd80-f79a-11ea-997c-c78c4b6c66fe.png)
![image](https://user-images.githubusercontent.com/17398401/93223817-a98f8180-f79a-11ea-962c-f821c9ce5a82.png)
![image](https://user-images.githubusercontent.com/17398401/93223835-ae543580-f79a-11ea-89c7-36ca110a959d.png)
![image](https://user-images.githubusercontent.com/17398401/93223858-b4e2ad00-f79a-11ea-8fe1-f9f5d71e6418.png)
![image](https://user-images.githubusercontent.com/17398401/93223871-b9a76100-f79a-11ea-81d7-c162fec350d9.png)
![image](https://user-images.githubusercontent.com/17398401/93223886-bdd37e80-f79a-11ea-876d-1f09eb91e776.png)
![image](https://user-images.githubusercontent.com/17398401/93223901-c1670580-f79a-11ea-9b67-01100f731b55.png)
Good luck =))

**Comment by iamvucms** [comment]
Dont forget to give me a star ^^

**Comment by sootood** [comment]
thanks a lot,

**Comment by makemagik** [comment]
Hey @iamvucms 

Hope you are well! Awesome script. I'm starting to learn React Native and this is hella fun!

I am wondering if you could export the db via the tools provided ?

https://console.cloud.google.com/firestore/import-export

Thanks !! :)

**Comment by iamvucms** [comment]
Hello @sootood, @makemagik 
I 've just exported firestore by this way: [https://www.youtube.com/watch?v=Xx0goSxpVqY&ab_channel=DroidpediaAcademy](url)
[db.zip](https://github.com/iamvucms/react-native-instagram-clone/files/5899727/db.zip)
Good luck.

**Comment by M-tech-cmd** [comment]
Finally I needed this guidance, thank you for this 😍
